export const CAMPSITES = [
    {
        id: 0,
        name: "React Lake Campground",
        image: "assets/images/react-lake.jpg",
        elevation: 1233,
        description: "Nestled in the foothills of the Chrome Mountains, this campground on the shores of the pristine React Lake is a favorite for fly fishers.",
        comments: [
            {
                id: 0,
                rating: 5,
                text: "What a magnificent view! (React Lake)",
                author: "Tinus Lorvaldes",
                date: "2018-10-25T16:30Z",
            },
            {
                id: 1,
                rating: 4,
                text: "The campground was beautiful, but the bugs could bite sometimes. (React Lake)",
                author: "Brennen Ech",
                date: "2017-06-17T03:33Z",
            },
            {
                id: 2,
                rating: 5,
                text: "I caught a world-record-breaking trout here on my last visit. (React Lake)",
                author: "McKenzie Sebastian",
                date: "2019-02-18T18:12Z",
            },
            {
                id: 3,
                rating: 5,
                text: "A wonderful place to reconnect with nature. (React Lake)",
                author: "Jordan Runn",
                date: "2019-08-04T20:11Z",
            },
            {
                id: 4,
                rating: 4,
                text: "The stars at night were magnificent! (React Lake)",
                author: "Ann Dabramov",
                date: "2018-07-23T19:44Z",
            },
        ],
    },
    {
        id: 1,
        name: "Chrome River Campground ",
        image: "assets/images/chrome-river.jpg",
        elevation: 877,
        description: "Spend a few sunny days and starry nights beneath a canopy of old-growth firs at this enchanting spot by the Chrome River.",
        comments: [
            {
                id: 0,
                rating: 5,
                text: "What a magnificent view! (Chrome River)",
                author: "Tinus Lorvaldes",
                date: "2018-10-25T16:30Z",
            },
            {
                id: 1,
                rating: 4,
                text: "The campground was beautiful, but the bugs could bite sometimes. (Chrome River)",
                author: "Brennen Ech",
                date: "2017-06-17T03:33Z",
            },
            {
                id: 2,
                rating: 5,
                text: "I caught a world-record-breaking trout here on my last visit. (Chrome River)",
                author: "McKenzie Sebastian",
                date: "2019-02-18T18:12Z",
            },
            {
                id: 3,
                rating: 5,
                text: "A wonderful place to reconnect with nature. (Chrome River)",
                author: "Jordan Runn",
                date: "2019-08-04T20:11Z",
            },
            {
                id: 4,
                rating: 4,
                text: "The stars at night were magnificent! (Chrome River)",
                author: "Ann Dabramov",
                date: "2018-07-23T19:44Z",
            },
        ],
    },
    {
        id: 2,
        name: "Breadcrumb Trail Campground",
        image: "assets/images/breadcrumb-trail.jpg",
        elevation: 2901,
        description: "Let NuCamp be your guide to this off-the-beaten-path, hike-in-only campground.",
        comments: [
            {
                id: 0,
                rating: 5,
                text: "What a magnificent view! (Breadcrumb)",
                author: "Tinus Lorvaldes",
                date: "2018-10-25T16:30Z",
            },
            {
                id: 1,
                rating: 4,
                text: "The campground was beautiful, but the bugs could bite sometimes. (Breadcrumb)",
                author: "Brennen Ech",
                date: "2017-06-17T03:33Z",
            },
            {
                id: 2,
                rating: 5,
                text: "I caught a world-record-breaking trout here on my last visit. (Breadcrumb)",
                author: "McKenzie Sebastian",
                date: "2019-02-18T18:12Z",
            },
            {
                id: 3,
                rating: 5,
                text: "A wonderful place to reconnect with nature. (Breadcrumb)",
                author: "Jordan Runn",
                date: "2019-08-04T20:11Z",
            },
            {
                id: 4,
                rating: 4,
                text: "The stars at night were magnificent! (Breadcrumb)",
                author: "Ann Dabramov",
                date: "2018-07-23T19:44Z",
            },
        ],
    },
    {
        id: 3,
        name: "Redux Woods Campground",
        image: "assets/images/redux-woods.jpg",
        elevation: 42,
        description: "You'll never want to leave this hidden gem, deep within the lush Redux Woods.",
        comments: [
            {
                id: 0,
                rating: 5,
                text: "What a magnificent view! (Redux Woods)",
                author: "Tinus Lorvaldes",
                date: "2018-10-25T16:30Z",
            },
            {
                id: 1,
                rating: 4,
                text: "The campground was beautiful, but the bugs could bite sometimes. (Redux Woods)",
                author: "Brennen Ech",
                date: "2017-06-17T03:33Z",
            },
            {
                id: 2,
                rating: 5,
                text: "I caught a world-record-breaking trout here on my last visit. (Redux Woods)",
                author: "McKenzie Sebastian",
                date: "2019-02-18T18:12Z",
            },
            {
                id: 3,
                rating: 5,
                text: "A wonderful place to reconnect with nature. (Redux Woods)",
                author: "Jordan Runn",
                date: "2019-08-04T20:11Z",
            },
            {
                id: 4,
                rating: 4,
                text: "The stars at night were magnificent! (Redux Woods)",
                author: "Ann Dabramov",
                date: "2018-07-23T19:44Z",
            },
        ],
    },
];
